### ISSUE TITLE
Review stats on Open Ed Stats page are incorrect

### ISSUE THREAD

**Issue by josieg** [BCcampus/opentextbooks#100]
### Description 

When looking at the review stats under the Review tab of the Open Ed website stats page, reviews either have 0 or 1 reviews. 

**Expected behaviour** 

I expect that the Reviews stats page should be displaying the correct number of reviews for each book, with the correct average score from all reviews for that book.

**Actual behaviour** 

All of the books under the Review stats tab either have 0 or 1 reviews. While all of the books with 0 reviews seem correct, many of the books in our collection have more than one review, but the stats page only seems to be counting the most recent review. 
Examples: 
- Canadian History: Pre-Confed (should show 4 reviews)
- Creative Clinical Teaching in the Health Profession (should show 5 reviews)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/opentextbooks/commit/e94b4508c9bec1225ddeb87a3c922398528383bd

**Comment by josieg** [comment]
Looks great! This can be closed.
