### ISSUE TITLE
[manitoba] search 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#108]
### Description 

The original request is to have a search box similar to the open site: 

![image](https://user-images.githubusercontent.com/2048170/46697386-60575000-cbc9-11e8-86c3-d71ff209e28e.png)

The caveat discussed is that there are two search boxes. One searches against the equella API, the other is a WP only search. 

**Expected behaviour** 

knowing that there is a caveat, leaving this open to see if this is still desired. 

**Actual behaviour** 

feature request

**Comment by dshaykewich** [comment]
@bdolor , I'm trying to write this user story.  Did you get clarification on this request regarding whether to search for books or pages in the site?

**Comment by bdolor** [comment]
If I'm not mistaken, I think the status of this could be something @nash7 might be able to answer?

**Comment by nash7** [comment]
Knowing this caveat of the additional search box,  leaves us with the decision that we no long would like the search box added.   Sorry for the delay on this.
