### ISSUE TITLE
New institution added to Adoption form

### ISSUE THREAD

**Issue by laesoph** [BCcampus/opentextbooks#12]
Trinity Western University (TWU) was added as an option to the **Select an institution** dropdown menu in the Adoption form.

Please add the baseline for this institution to https://github.com/BCcampus/opentextbooks/blob/dev/includes/Models/WebForm.php#L66

The baseline for TWU is 1 adoption, 25 students, and a total savings of $2000.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/opentextbooks/pull/44
