### ISSUE TITLE
allow for application to be brought in as a dependency

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#129]
**Is your feature request related to a problem? Please describe.**
Since the front end of this application is loosely coupled, it will be relatively easy to access the application's functionality and pass the responsibility of look and feel over to a theme instead of having to rely on the application for look and feel concerns. 

**Describe the solution you'd like**
I'd like to be able to `composer install BCcampus/opentextbooks` 
- configuration options currently rely on a `.env.somedomain.php` file - I'd like to be able to introduce another way to set up the config that doesn't rely on a file that would get overwritten with each `composer up` 

**Describe alternatives you've considered**
Currently we can `iframe` the application inside WP pages, which works, keeps the two separate, but is not ideal for a number of reasons. 

**Additional context**
As a developer of a wordpress theme
I would like to be able to pull this application in as a dependency of my theme
So that I can access all its functionality and not be bound to iframing the existing 'views' currently available

**Comment by bdolor** [comment]
Note: though it would still be desirable to pull this in as a dependency, it has been designed to be a stand alone application and will require more time than is available in the current sprint to refactor. Keeping this as a standalone also benefits use cases where this application is used outside open-sage theme (i.e. Manitoba & Ontario)

**Comment by ehbeattie** [comment]
Ok. What are the next steps for this one, @bdolor?

**Comment by bdolor** [comment]
if entering a search term in the search component on the homepage takes you to the application (which displays all textbooks) then validation is complete.

**Comment by ehbeattie** [comment]
Ok, perfect.
