### ISSUE TITLE
Featured guides and toolkits 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#130]
**Is your feature request related to a problem? Please describe.**
In order to support https://github.com/BCcampus/open-sage/issues/10 equella admins need the ability to manually select which guides and toolkits receive a featured status

**Describe the solution you'd like**
Similar to how lists (adopted, ancillary resources, reviewed) are currently generated with a custom element in equella, featured guides and toolkits needs to be created. Once created on the equella end, this application needs to be configured to deliver only those elements in the open textbook collection that are marked with that element. 

**Describe alternatives you've considered**
Randomly selecting guides and toolkits from that particular subject area in the collection.

**Additional context**
As a content owner
I would like to curate guides and toolkits 
So that I can display them on the open site

**Comment by bdolor** [comment]
complete via https://github.com/BCcampus/open-sage/commit/7f3cdfd4a213354bf19e11015e32a36e7ca6ce5e 

can be validated on https://helga.bccampus.ca/wp/opentextbooks/ including adding attribute in equella for control 

![image](https://user-images.githubusercontent.com/2048170/53592330-e2312100-3b4a-11e9-9bbb-342fb40d719b.png)

**Comment by josieg** [comment]
Josie to validate

**Comment by josieg** [comment]
I added four guides using this feature this morning, but helga has still not updated. Since I will not be here on Monday, someone else can validate this issue by confirming that the following guides appear in the "Getting Started" section on the home page:
- Pulling Together
- Self-Publishing Guide
- Accessibility Toolkit
- Faculty OER Toolkit

**Comment by ehbeattie** [comment]
Confirmed that the following guides appear in the "Getting Started" section on the home page:

Pulling Together
Self-Publishing Guide
Accessibility Toolkit
Faculty OER Toolkit
