### ISSUE TITLE
[65.4] Investigate fitlering search results 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#135]
**Is your feature request related to a problem? Please describe.**
Filtering search results against resources with specific attributes is meant to address a potential user preference.

**Describe the solution you'd like**
Search terms would generate a list of relevant resources and be further limited by one of four attributes, selected by a drop down list. 

Further iterations of this feature may want to address one _or more_ attributes and be triggered by selecting one or more checkboxes.

**Describe alternatives you've considered**
Since the API that Equella provides is not designed to accept filtering preferences based on arbitrary metadata, alternatives would be to re-visit the cost/benefit of fleshing out this feature request.

**Comment by ehbeattie** [comment]
Check!
