### ISSUE TITLE
[65.5] styling parity

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#136]
**Is your feature request related to a problem? Please describe.**
styling of the find open textbooks page has been updated 

**Describe the solution you'd like**
The work captured here is to look at the page as a whole, and resolve any obvious inconsistencies with respect to look and feel such as alignment, icons, borders, colours, etc.

**Describe alternatives you've considered**
N/A

**Comment by ehbeattie** [comment]
Holy cats! This is actually starting to come together!
