### ISSUE TITLE
[78.1] Grouping attachments on single record display

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#137]
**Is your feature request related to a problem? Please describe.**
Indicating whether or not a file is 'editable' is intended to provide a specific context around what can be done with the files post-download.

**Describe the solution you'd like**
'Readable' files will be of the file type .pdf, 'online' (a URI), .epub, .mobi, .hpub
'Editable' files will be .xml, .html, .odt, .docx, .doc, ._vanilla.xml, .rtf, .tex, .zip (If URI is pointing at GH domain, that file is considered Editable. )
'Buy a Print Copy' will be 'online' (URI) with the sfu document solutions domain (currently opentextbook.docsol.sfu.ca)
'Ancillary Resource' string match for "ancillary resource" at the start of the string
 
filetypes listed here: https://github.com/BCcampus/opentextbooks/blob/dev/inc/views/class-books.php#L626 

**Describe alternatives you've considered**
There is a desire to group Ancillary resources, but finding a mechanism/attribute for separation has yet to be determined

**Comment by alex-418** [comment]
@ehbeattie since the decision of keeping the side nav on this page was made, that also meant keeping the attachments where they are...  so I had concerns with the length of this list on some pages (took up a lot of vertical space). This is the solution I came up with to solve that problem, for discussing at stand-up in the AM.

![grouping](https://user-images.githubusercontent.com/17072191/54000361-e84f7080-40fb-11e9-8958-0ebe59603b52.png)

**Comment by alex-418** [comment]
@josieg noticed an inconsistency with the prefix of Ancillary Resources ... in some resources is plural while others it is not. So my question is if it's easy/quick for you to update al of these so they are consistent? If the answer is no, then i'll have to look for both variations in my code.

**Comment by josieg** [comment]
Yes. I will be updating all so that "Ancillary Resource" is singular.

**Comment by alex-418** [comment]
Thank you, will use singular in code.

**Comment by alex-418** [comment]
@josieg just thought i'd also mention, that for the "Buy print copy" group... i'm checking to see if it's a URL to the docsol sfu domain... OR if it has the string "**print copy**" in it.

**Comment by josieg** [comment]
Most "Buy a print copy" links are links to https://opentextbook.docsol.sfu.ca/, but not all. So I think looking for a "Buy a print copy" string in the file label would be better.

**Comment by bdolor** [comment]
Alex is describing functionality that currently exists, which satisfies a requirement made long ago to have two ways to control the label...would recommend leaving the logic as is

**Comment by ehbeattie** [comment]
Looks great!

**Comment by alex-418** [comment]
@ehbeattie @josieg hello can you guys confirm how editable files will be identified? I'm trying to lock down a fix for editable files which are URL's that are showing up in the readable group ... i've added logic to search if it contains "editable" ... is there any variations of this? Any plural version, or any case where the word editable would not be in the prefix?

**Comment by alex-418** [comment]
Here's an example of an editable file showing up in the readable group:
https://helga.bccampus.ca/wp/opentextbooks/find-open-textbooks/?uuid=a2698989-dc9d-4350-b8ee-0a5c71729881&contributor=&keyword=&subject=

I've got a fix ready, just need to confirm the logic needed to capture all editable files.

**Comment by josieg** [comment]
Hi Alex, I believe we agreed that editable files would be identified by file type, i.e. by file extension (as described in Brad's initial description of this issue) and I thought I could make sure links were always only readable files. But I forgot about the exception for OpenStax books, where we link to the Pressbooks webbook version (not editable but can be cloned into Pressbooks to be edited).

I have two thoughts on this:

- either you leave this instance as a readable file and I will make sure to change the label to make it clear, - Or if you could add an exception to files that retain an "Editable" prefix in the label and put them in the Editable group, regardless of file type (but still use file extension for sorting rest of editable files)

Either way, I leave the decision of how to handle it up to you. All I care about is that files are sorted into the correct categories.
