### ISSUE TITLE
[78.2] List nested subject areas on individual book record

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#138]
**Is your feature request related to a problem? Please describe.**
As a quasi-navigational component, similar to lightweight breadcrumbs, it would indicate where in the nested structure of subject areas the book belongs.

**Describe the solution you'd like**
Subject level 1 will not be linked, subject level 2 will be linked

**Describe alternatives you've considered**
Mimicking the functionality of WP breadcrumbs.

**Comment by ehbeattie** [comment]
Looks good!
