### ISSUE TITLE
[78.3] display posted on/updated on dates 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#139]
**Is your feature request related to a problem? Please describe.**
Intended to clear up confusion around the current, vague label 'date'

**Describe the solution you'd like**
Do this: 
![image](https://user-images.githubusercontent.com/2048170/53270483-a7d60880-36a0-11e9-85fb-22387dd39e65.png)

**Comment by ehbeattie** [comment]
👍
