### ISSUE TITLE
[78.5] Rename and move adoptions link

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#141]
**Is your feature request related to a problem? Please describe.**
I'm not clear on the reasoning behind this change.

**Describe the solution you'd like**
Change to `Tell us you're using this Open Textbook`

**Comment by bdolor** [comment]
this change is handled in a config file that is not under version control. The change to the config file have been made on cert _and_ prod

**Comment by ehbeattie** [comment]
Looks like a link with the correct verbiage and in the right spot. Check!
