### ISSUE TITLE
Update labels on ancillary resource files in SOLR

### ISSUE THREAD

**Issue by josieg** [BCcampus/opentextbooks#151]
Here is a list of all books with Ancillary Resources: https://open.bccampus.ca/find-open-textbooks/?lists=ancillary

I need to go into SOLR and for each book, change the label on all ancillary resource files so they read "Ancillary Resource: XXX" Currently, files may be titled Instructor Resource/Student Resource/Ancillary Resources

This work should be done before the new website goes live.

**Comment by josieg** [comment]
I am unable to assign or add labels. Can someone assign this to me and add a non-dev label?

**Comment by bdolor** [comment]
you should now be able to do the things...

**Comment by josieg** [comment]
This work is covered in issue #152 so closing.
