### ISSUE TITLE
Remove line from Open Textbook Stats page

### ISSUE THREAD

**Issue by kkilbey** [BCcampus/opentextbooks#165]
On the Open Textbook Stats page, we'd like to remove this line of text: "Savings include a range as reported in our blog, Calculating Student Savings." The link goes to a blog post, and the new Open site no longer includes the blog. This is a dev task, as we cannot edit the stats page.

See image:
![image](https://user-images.githubusercontent.com/44710357/55825335-a333ab00-5aba-11e9-9009-df265a2cb5d5.png)

Link to Open Textbook Stats page: https://open.bccampus.ca/advocate-for-open-education/open-textbook-stats/

**Comment by alex-418** [comment]
Text removed via https://github.com/BCcampus/open-sage/commit/59c526ea41dd3a08ef25121d2a4f0e01b1cebbb4
