### ISSUE TITLE
[View DspaceBooks->displayOneTextbook] DSpace API

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#30]
similar to https://github.com/BCcampus/opentextbooks/blob/dev/includes/Views/Books.php#L50 this function needs to return HTML with all elements required when displaying one textbook from DSpace. 

Example: 
![image](https://cloud.githubusercontent.com/assets/2048170/26534944/d0047164-43dd-11e7-9e3f-5898b5500483.png)

**Comment by alexpflores** [comment]
Cover image will be completed via #54 (has a dependency on #53), any missing attachments will be added via #56.

**Comment by alexpflores** [comment]
![attachments](https://cloud.githubusercontent.com/assets/17072191/26748292/3bd01ac0-47b1-11e7-9f51-188ae46cd1dd.png)
