### ISSUE TITLE
[View DspaceBooks->determineFileSize] DSpace API

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#36]
similar to https://github.com/BCcampus/opentextbooks/blob/dev/includes/Views/Books.php#L832 this function returns the file size of an attachment in a human readable format. Must verify if DSpace API provides this information. 

Example: 

![image](https://cloud.githubusercontent.com/assets/2048170/26535813/9e65f9ae-43e5-11e7-9d56-2ed9aeb7d8a9.png)

**Comment by bdolor** [comment]
confirming this is possible with DSpace API. Endpoint is: 

`{https://yourDspaceInstance.com}/rest/items/{itemUUID}?expand=bitstreams`

see `sizeBytes` element below: 

![image](https://cloud.githubusercontent.com/assets/2048170/26562679/5d7eb79e-447d-11e7-9f82-e790220abb48.png)

**Comment by alexpflores** [comment]
Completed as part of #30 
![attachments](https://cloud.githubusercontent.com/assets/17072191/26747238/615f88e6-47a9-11e7-9a30-884b7f943b4e.png)
