### ISSUE TITLE
[View DspaceBooks->addLogo] DSpace API

### ISSUE THREAD

**Issue by bdolor** [BCcampus/opentextbooks#37]
similar to https://github.com/BCcampus/opentextbooks/blob/dev/includes/Views/Books.php#L864 this function returns a file logo depending on the type of attachment file. 

Example: 

![image](https://cloud.githubusercontent.com/assets/2048170/26535862/38497456-43e6-11e7-9061-300871e577ce.png)

**Comment by bdolor** [comment]
confirming this is possible with DSpace API. Endpoint is: 

`{https://yourDspaceInstance.com}/rest/items/{itemUUID}?expand=bitstreams`

see `mimeType` element below: 

![image](https://cloud.githubusercontent.com/assets/2048170/26562679/5d7eb79e-447d-11e7-9f82-e790220abb48.png)

**Comment by alexpflores** [comment]
Function completed via 7e050ccfb345c879c42ac00abbb773b25165baa4
