### ISSUE TITLE
[custom submission form] Requirements for Contribution fields

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#40]
Title
Description
Upload textbook
Adaptation (does an adaptation of this book exist?) yes/no
Reviewed (Has this textbook been reviewed by at least one instructor in BC? ) yes/no
Ancillary Resources (Does this item have ancillary resources available? ) yes/no
License: Choose a Creative Commons license for this textbook
Link back to the original source
Discipline -see issue https://github.com/BCcampus/opentextbooks/issues/41
Institutional Partners (see issue) https://github.com/BCcampus/opentextbooks/issues/42
Language of Resource (English french japanese spanish chinese)
Cover Image: A URL pointing to an image resource https://github.com/BCcampus/opentextbooks/issues/53
Image Copyright: Copyright Attribution statement for cover images used for Open Textbooks
Revision date: If the textbook is currently being revised, set the date it is scheduled for release
Accessibility: Has this textbook been reviewed for accessibility? Y/no
Adoption: Has this textbook been adopted by at least one faculty in B.C.? Y/n
Contributors (field for names)

**Comment by bdolor** [comment]
duplicate issue in jira
