### ISSUE TITLE
Discipline requirements under contribution

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#41]
Disciplines
Business and Management:

- Accounting
- Business Technology
- Commerce
- Economics
- Human Resources and Organizational Behavior
- Management
- Marketing

Health
</div><select id="c16_left" multiple="multiple" size="10"><option value="Animal Health/Science" selected="selected">Animal Health/Science</option>
<option value="Dental Related" selected="selected">Dental Related</option>
<option value="Diagnostic Technology &amp; Related" selected="selected">Diagnostic Technology &amp; Related</option>
<option value="Environmental/Occupational Health" selected="selected">Environmental/Occupational Health</option>
<option value="Health Care Administration" selected="selected">Health Care Administration</option>
<option value="Health Information/Medical Records" selected="selected">Health Information/Medical Records</option>
<option value="Health/Medical - General" selected="selected">Health/Medical - General</option>
<option value="Home Support/Resident Care Related" selected="selected">Home Support/Resident Care Related</option>
<option value="Medical Laboratory Related" selected="selected">Medical Laboratory Related</option>
<option value="Medical Office/ Administrative Related" selected="selected">Medical Office/ Administrative Related</option>
<option value="Nutrition and Dietary Related" selected="selected">Nutrition and Dietary Related</option>
<option value="Optical/Eye Care Related" selected="selected">Optical/Eye Care Related</option>
<option value="Pharmacy/Pharmacology Related" selected="selected">Pharmacy/Pharmacology Related</option>
<option value="Physicians and Surgeons" selected="selected">Physicians and Surgeons</option>
<option value="Practical Nursing (LPN) Related" selected="selected">Practical Nursing (LPN) Related</option>
<option value="Psychiatric/Mental Health Nursing" selected="selected">Psychiatric/Mental Health Nursing</option>
<option value="Registered Nursing (RN) Related">Registered Nursing (RN) Related</option>
<option value="Rehabilitation/Therapeutic Services">Rehabilitation/Therapeutic Services</option>

Liberal Arts and Humanities
- Philosophy
- English
- Communication
- French
- Art Media and Design
- History

Sciences
- Biology
- Chemistry
- Math/statistics
- Computer Science
- Physics
- Earth, Ocean, Atmospheric Sciences
- Kinetics and Kinesiology
- Applied Science
- Geography

Social Sciences
- Psychology
- Sociology
- Anthropology
- Political Science
- Criminology

Trades
- Pipe Trades
- Professional Cook
- Trades Access Common Core

Recreation/Tourism
</div><select id="c17_left" multiple="multiple" size="10"><option value="Adventure Tourism">Adventure Tourism</option>
<option value="Baking/Cooking/ Chef Training">Baking/Cooking/ Chef Training</option>
<option value="Esthetics/Skin Care">Esthetics/Skin Care</option>
<option value="Food/Beverage Services">Food/Beverage Services</option>
<option value="Hairstyling">Hairstyling</option>
<option value="Hospitality/Tourism - General">Hospitality/Tourism - General</option>
<option value="Hospitality/Tourism Management">Hospitality/Tourism Management</option>
<option value="Human Kinetics/ Kinesiology/ Physical Education">Human Kinetics/ Kinesiology/ Physical Education</option>
<option value="Meat Cutting">Meat Cutting</option>
<option value="Parks, Recreation &amp; Leisure Facilities Management">Parks, Recreation &amp; Leisure Facilities Management</option>
<option value="Recreation Leadership Related">Recreation Leadership Related</option>
<option value="Sports and Fitness Administration/ Management">Sports and Fitness Administration/ Management</option>
<option value="Travel Industry Related">Travel Industry Related</option>

Upgrading Programs:
Academic/Basic Upgrading
Adult Special Education
Employment Preparation
English as a Second Language
Trades/Technology Access and Bridging

**Comment by bdolor** [comment]
duplicate, jira
