### ISSUE TITLE
Issue date and time when in OT Collection homepage

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#45]
Time and data strand seems overly complicated. Can we simplify?
![screen shot 2017-05-29 at 2 27 44 pm](https://cloud.githubusercontent.com/assets/23705492/26562442/1d5e8290-447b-11e7-9482-c1a93c532f77.png)

https://dspace.bccampus.ca/jspui/handle/20.500.11985/4

**Comment by bdolor** [comment]
moved issue to appropriate code base.
