### ISSUE TITLE
Discover panel on right side of page

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#47]
Currently the discover panel shows author- can we change this to a list of subject areas?
https://dspace.bccampus.ca/jspui/handle/20.500.11985/4
![screen shot 2017-05-29 at 2 31 18 pm](https://cloud.githubusercontent.com/assets/23705492/26562519/a7b95550-447b-11e7-9257-75862f096c57.png)

**Comment by bdolor** [comment]
moving issue to jira
