### ISSUE TITLE
Under Browse add another category

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#48]
Within the Browse bar can we add File Type?
- add the multiple file types

https://dspace.bccampus.ca/jspui/handle/20.500.11985/4

![screen shot 2017-05-29 at 2 35 17 pm](https://cloud.githubusercontent.com/assets/23705492/26562563/2900c30a-447c-11e7-8951-38cc9098082e.png)

**Comment by bdolor** [comment]
nothing to do with code base, closing, moving to jira
