### ISSUE TITLE
Main page add another section

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#49]
Please add Subject Areas
Change Has File to File Type
https://dspace.bccampus.ca/jspui/

![screen shot 2017-05-29 at 2 40 46 pm](https://cloud.githubusercontent.com/assets/23705492/26562643/f740b68a-447c-11e7-86c0-032b2a5a8ef6.png)

**Comment by bdolor** [comment]
issue does not pertain to code base, closing, moving to jira
