### ISSUE TITLE
Once logged in- not sure what to do

### ISSUE THREAD

**Issue by acoolidge** [BCcampus/opentextbooks#50]
Not sure what it means add a new submission and view accepted submissions.
I think once you log in you should go start to BC Open Education Repoistory homepage.

![screen shot 2017-06-01 at 10 04 54 am](https://cloud.githubusercontent.com/assets/23705492/26691412/dac50204-46b1-11e7-95b8-da181dbb9833.png)

**Comment by bdolor** [comment]
Closing this ticket - has nothing to do with the code base. Re-creating ticket in JIRA
