### ISSUE TITLE
[custom submission form] Cover Image field in dspace submission form 

### ISSUE THREAD

**Issue by alexpflores** [BCcampus/opentextbooks#53]
Add a field to allow users to upload the cover image for their book, and resize it to 151x196. 

Documentation on how to change the submission form:
https://wiki.duraspace.org/display/DSDOC6x/Submission+User+Interface#SubmissionUserInterface-AssigningacustomSubmissionProcesstoaCollection

**Comment by bdolor** [comment]
duplicate, jira
