### ISSUE TITLE
Missing attachments for a textbook, figure out how to get their values

### ISSUE THREAD

**Issue by alexpflores** [BCcampus/opentextbooks#56]
Need to create the following fields in dspace submission form, and get their values another way:

- Buy a print copy URL 
- Read this book online URL 
- Read this book online (for all other languages) URL(s)
- PDF (for all other languages) URL(s) 
- Kindle .MOBI URL 
- Other Files/Resources (website/audio books) URL(s)

**Comment by bdolor** [comment]
DSpace development is no longer moving ahead — closing.
