### ISSUE TITLE
Change licence on all open textbook reviews submitted after March 15, 2018 to CC BY

### ISSUE THREAD

**Issue by josiegray** [BCcampus/opentextbooks#91]
**Description of the bug or feature**
The Open Education team would like to change the licence on open textbook reviews posted in the BCcampus, eCampusOntario, and Campus Manitoba Open Textbook collections. Currently, reviews are labelled with a CC BY-ND licence (See below image or this [link.)](https://open.bccampus.ca/find-open-textbooks/?uuid=d7fed8c0-e900-4bef-b414-14f48122cba2&contributor=&keyword=&subject=) We would like all reviews submitted on or after March 15, 2018, labelled with a CC BY licence. Reviews submitted before that date should retain the CC BY-ND licence. 

![image](https://user-images.githubusercontent.com/37554861/38960595-f168a15e-4319-11e8-8118-156a6e3e4837.png)

**Expected behaviour** 

We want all reviews that are submitted through LimeSurvey on or after March 15, 2018, to display in the BC/Manitoba/Ontario open textbook collections with a CC BY licence. We want reviews submitted before this date to retain the CC BY-ND licence.

**Actual behaviour** 

As it is now, all reviews posted in the BC/Ontario/Manitoba collections are marked with CC BY-ND licences.

Thanks! Let me know if you need anything more from me.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/opentextbooks/commit/8561eeabcd6add68b0140b43fe7b67c07d4d8dd5
