### ISSUE TITLE
opentextbc.ca download stats are incorrect

### ISSUE THREAD

**Issue by josieg** [BCcampus/opentextbooks#99]
### Description 

The download stats for each book listed under the opentextbc.ca tab on the [Open website stats page](https://open.bccampus.ca/open-textbook-stats/) are incorrect. The visits/actions/pageviews stats on the first page seem accurate. But when you click on the "Download Stats" link next to each book, you are taken to the download-stats page showing incorrect numbers.

**Expected behaviour** 

I expect the download stats for each book to vary depending on their popularity and for the download stats to be at least a comparable to the visits/actions/pageviews stats. 

**Actual behaviour** 

The download-stats page for each book under the "opentextbc.ca" stats tab looks the exact same and displays the following set of numbers:

![stats](https://user-images.githubusercontent.com/23706762/46098824-15295000-c17a-11e8-9abf-f6337d50e51b.JPG)

**Comment by bdolor** [comment]
that's an interesting bug! Thanks Josie.

**Comment by josieg** [comment]
Note: The numbers have gone up since I reported this, but all books still show a matching set of numbers (I checked three different random books). Here is a screenshot from today:
![stats](https://user-images.githubusercontent.com/23706762/48428688-625c8380-e720-11e8-8a48-1d2472085018.JPG)

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/opentextbooks/commit/4d4c1298a2883155addde232b8d13ff282f7e5bf

**Comment by josieg** [comment]
Looks good. I think we can close this.
